
stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

variables:
  DATABASE_URL: ""

lint-job:
  image: python:3-bullseye
  stage: test
  script:
    - pip install flake8
    - flake8 api/models/reviews.py api/models/restaurants.py
    - flake8 api/routers/reviews.py api/routers/restaurants.py
    - flake8 api/db.py

build-front-end-job:
  stage: build
  image: node:lts-bullseye
  script:
    - cd ghi
    - npm install
    - npm run build

restaurant-unit-test-job:
  image: python:3-bullseye
  stage: test
  script:
    - cd api
    - pip install -r requirements.txt
    - python -m pytest
